services:
  
  db:
    image: postgres
    restart: always
    ports: 
      - "6543:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: microservices_db
      POSTGRES_PASSWORD: example
  
  api-gateway:
    build: 
      dockerfile: api-gateway/Dockerfile
      context: ./
    ports:
      - "4000:80"
    depends_on:
      - product-service
      - customer-service
      - order-service

  product-service:
    build: 
      dockerfile: services/product-service/Dockerfile
      context: ./
    ports:
      - "4001:5000"
    depends_on:
      - db

  customer-service:
    build: 
      dockerfile: services/customer-service/Dockerfile
      context: ./
    ports:
      - "4002:4002"
    depends_on:
      - db
  
  order-service:
    build: 
      dockerfile: services/order-service/Dockerfile
      context: ./
    ports:
      - "4003:5000"
    depends_on:
      - db

  

